<section id="createFolder" class="page">
    <section id="createHiitPopup" class="hidden">
    <p id="createHiitPopupMessage"></p>
    </section>
        <h1>Create HIIT</h1>
        <p>Create your own personalised HIIT</p>
            <label for="folderName">Name</label>
            <input type="text" id="folderName" name="folderName" required>

            <label for="folderDescription">Description</label>
            <textarea id="folderDescription" name="folderDescription"></textarea>
            <button type="submit" id="createFolderButton">Create</button>
            
    </section>